apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: example.spring/skaffold
    docker:
      buildArgs:
        JAR_NAME: "skaffold"
        VERSION: "0.0.1"
        PORT: "80"
deploy:
  kubectl:
    manifests:
    - k8-*