apiVersion: v1
kind: Service
metadata:
  name: pet
  labels:
    app: pet
spec:
  ports:
  - port: 80
    nodePort: 30000
    name: http
  selector:
    app: pet
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet
  labels:
    app: pet
spec:
  selector:
    matchLabels:
      app: pet
  template:
    metadata:
      labels:
        app: pet
    spec:
      containers:
      - name: pet
        image: service-pet
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        env:
        - name: _JAVA_OPTIONS
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1"