apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: store-service
spec:
  gateways:
  - gateway
  - mesh
  http:
  - match:
      uri:
        prefix: /*
    route:
    - destination:
        name: store